config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
    end
    resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :ingredient, scope: [:cocktail]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to(cocktail_path(@cocktail))
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    # redirect_to cocktail_path(@dose.cocktail)
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="flex-wrapper">


  <div class="container">

    <div class="header">
      <h1>/cocktails</h1>
    </div>

    <div class="left-side"></div>

    <div class="body-content">
        <% @cocktails.each do |cocktail| %>
          <p><%= link_to(cocktail.name, cocktail_path(cocktail.id)) %></p>
        <% end %>
    </div>

    <div class="right-side"></div>

    <div class="footer">
      <h2><%= link_to("create a cocktail", new_cocktail_path) %></h2>
    </div>
  </div>

</div>

app/views/cocktails/new.html.erb
<h1>/cocktails/new</h1>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.submit "add a cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="flex-wrapper">

  <div class="container">

    <div class="header">
      <h3>/cocktails/:id/show</h3>
    </div>

    <div class="left-side"></div>

    <div class="body-content">
      <p><%= @cocktail.name %></p>
        <% @cocktail.doses.each do |dose| %>
          <p>
            <%= dose.description %>
            <%= dose.ingredient.name %>
            <%= link_to(dose_path(dose), method: :delete) do %>
              <i class="far fa-trash-alt"></i>
            <% end %>

          </p>
        <% end %>

      <h6><%= link_to("create a dose", new_cocktail_dose_path(@cocktail)) %></h6>
    </div>

    <div class="right-side"></div>

    <div class="footer">
      <h3><%= link_to("back", cocktails_path) %></h3>
      <h3><%= link_to("create a cocktail", new_cocktail_path) %></h3>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<h1>/cocktails/:cocktail_id/doses/new</h1>

<!-- simple form -->
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "add a dose", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>